setting:
 https.proxy:
 scraping_url: https://docs.nginx.com/nginx-ingress-controller/
 deepl_enable: false
 deepl_apikey: "todo"

jrnote:
- overviewAbout
- overviewDesign
- overviewNginxPlus
- overviewProductTelemetry

overviewAbout_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/overview/about/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

overviewDesign_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/overview/design/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

overviewNginxPlus_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/overview/nginx-plus/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

overviewProductTelemetry_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/overview/product-telemetry/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]
