setting:
 https.proxy:
 scraping_url: https://docs.nginx.com/nginx-ingress-controller/
 deepl_enable: false
 deepl_apikey: "todo"

jrnote:
- technicalSpecifications

technicalSpecifications_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/technical-specifications/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]
