setting:
 https.proxy:
 scraping_url: https://docs.nginx.com/nginx-ingress-controller/
 deepl_enable: false
 deepl_apikey: "todo"

jrnote:
- configurationGlobalConfigCommandLineArgs
- configurationGlobalConfigGlobalConfigResource
- configurationGlobalConfigConfigMapResources
- configurationGlobalConfigManagementConfigMapResource
- configurationGlobalConfigCustomTemplates
- configurationGlobalConfigReportingResourceStatus
- configurationIngressBasicConfig
- configurationIngressAdvancedConfigWithAnnotations
- configurationIngressCustomAnnotatons
- configurationIngressAdvancedConfigWithSnippets
- configurationIngressCrossNamespaceConfig
- configurationSecurityRecommendations
- configurationConfigEample
- configurationPolicyResource
- configurationTransportServerResources
- configurationVirtualServerAndVirtualServerRouteResources
- configurationHostAndListenerCollisions
- configurationProxyBufferConfigurationAutoAdjustment
- configurationDeployPolicyForAccessControl

 #
 # globalConfig
 #
configurationGlobalConfigCommandLineArgs_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/command-line-arguments/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationGlobalConfigGlobalConfigResource_scraping:
 url:  https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/globalconfiguration-resource/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationGlobalConfigConfigMapResources_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationGlobalConfigManagementConfigMapResource_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/mgmt-configmap-resource/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationGlobalConfigCustomTemplates_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/custom-templates/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationGlobalConfigReportingResourceStatus_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/reporting-resources-status/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

 #
 # ingressResource
 #
configurationIngressBasicConfig_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationIngressAdvancedConfigWithAnnotations_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationIngressCustomAnnotatons_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/custom-annotations/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationIngressAdvancedConfigWithSnippets_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-snippets/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationIngressCrossNamespaceConfig_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/cross-namespace-configuration/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

#
# securityRecommendations
#
configurationSecurityRecommendations_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/security/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationConfigEample_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/configuration-examples/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationPolicyResource_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/policy-resource/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationTransportServerResources_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/transportserver-resource/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationVirtualServerAndVirtualServerRouteResources_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationHostAndListenerCollisions_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/host-and-listener-collisions/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationProxyBufferConfigurationAutoAdjustment_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/proxy-buffers-configuration/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]

configurationDeployPolicyForAccessControl_scraping:
 url: https://docs.nginx.com/nginx-ingress-controller/configuration/access-control/
 section: //h1
 componet: ./following-sibling::*[self::h2 or self::h3]
